### ISSUE TITLE
【P】現アルゴリズムでのキーパー機体の対処

### ISSUE THREAD

**Issue by ChisatoKasebayashi** [ChisatoKasebayashi/Dorayaki#1]
ちゃんと横飛びしてボールを止める動作はしてるけど結果としてボールを止めれててない
→どうして？
→先輩が言ってた何フレームごとにボールが見えてるかを調べる（ログとしてとる）_ソース読まなきゃいけないのー？_
→先輩が言ってた重い計算処理を少しでも削ればボールを止められるっていう根拠は何なのか
→根拠があったとして、それは現実的な対処法なのか代替案を考える必要はないのか

**Comment by DaikiMaekawa** [comment]
@ChisatoKasebayashi 因みに今のアルゴリズムでどの程度フレームレートが出ていますか?

**Comment by ChisatoKasebayashi** [comment]
遅れてすみません、
一秒間におよそ１５回ボールを認識しています。
もし私のフレームレートの認識が間違っていたらご指導ください。

**Comment by DaikiMaekawa** [comment]
> 一秒間におよそ１５回ボールを認識しています。

HPL全体での周期のことです。 HLGameMonitorに表示されているものですね。

**Comment by ChisatoKasebayashi** [comment]
ありがとうございます、今から確認します。

**Comment by DaikiMaekawa** [comment]
去年からアルゴリズムの変更があったりしたため目安程度に考えて欲しいけど、10fpsを下回るとキーパのパフォーマンス的には致命的でした。

**Comment by ChisatoKasebayashi** [comment]
HLGameMonitorで確認したところ、１３ｆｐｓと表示されていました。

**Comment by DaikiMaekawa** [comment]
戦略側から見たらその数字は十分な値です。 キーパが活躍した去年の準決勝もその程度の値だったと思います。 そうなるとやはり、新ルールによるボール認識率の低下が関係してそうですね。 ボールの位置追跡はパーティクルフィルタを使ってるんでしたっけ?

**Comment by ChisatoKasebayashi** [comment]
はい、パーティクルフィルタだと聞いています。

**Comment by DaikiMaekawa** [comment]
よりボールの観測が不安定になったためフィルタを介す必要性がでてきたのだと推測しますが、その分rawデータを使用する場合に比べて反応は遅くなるはずです。 現状キーパが機能していないなら、フィルタに手を加える or ボールの認識率を上げてrawデータ(フィルタリングしない)をそのまま戦略側で使用するという選択肢がありますね。 または、現状の認識率でrawデータをそのまま使用した場合、戦略が安定して動作する見込みはありますか?

**Comment by ChisatoKasebayashi** [comment]
ごめんなさい、先輩の提示してくださった案について、私には判断する知識も確認する方法もわからないので、具体的にどうすればいいか教えてもらえますか

**Comment by DaikiMaekawa** [comment]
チームのシステムの細かい部分についてはあまりここで話さない方がいいかもしれません。(public リポジトリなので)

以前私がfacebookに送ったgitterというチャットサービスを覚えていますか?
https://gitter.im/citbrains

こちらで話し合うというのはどうでしょうか?

**Comment by ChisatoKasebayashi** [comment]
確かにパブリックなのでもうちょっと慎重に行動すべきでした、すみません
Gitterインストールします。よろしくお願いします。

**Comment by DaikiMaekawa** [comment]
でも、ここで様々なアルゴリズムを試しに実装してみたりするのは全然良い事だと思いますよ :+1:

**Comment by ChisatoKasebayashi** [comment]
ありがとうございます、関君といろいろやってます:smile:
最近は楽しいです

Gitter使えるようになりました、CitBrainsのroomに入れました。

**Comment by ChisatoKasebayashi** [comment]
世界大会中の教授の改良によりある程度は反応できていたのでこのissueは閉じます。
