### ISSUE TITLE
四則演算のできる電卓を作ろう！

### ISSUE THREAD

**Issue by ChisatoKasebayashi** [ChisatoKasebayashi/Dorayaki#5]
要求仕様は、
1、四則演算ができること

使う関数は
printf scanf switch while for if
こんな感じのがあります、グーグル先生に聞けばもっとたくさん便利な関数があるかもしれないので自分で調べて使ってみると面白いかもしれないです

**Comment by ChisatoKasebayashi** [comment]
完成したらfor_freshmenフォルダにソースを追加してリモートにプッシュしてください。
githubの練習も兼ねているのでいろいろ試してみてください。

**Comment by yotaseki** [comment]
stdio.hだけでなくstdlib.hなど他のヘッダも使ってどんどん機能を増やすと楽しいですよ

**Comment by RikiHayashi** [comment]
了解しました。

**Comment by RyoheiGoto** [comment]
了解です。

**Comment by RyoheiGoto** [comment]
Githubを使うのに少しトラブルがありましたがとりあえず出来ました

**Comment by DaikiMaekawa** [comment]
@GotoRyohei :+1: LGTM

しかし、これでは式をまとめて計算させることが出来ませんね。 (ex. 2 \* sin(M_PI) + (4 / 2)^2)
余力があれば逆ポーランド記法を使った実装にチャレンジしてみるのはどうですか? プログラミングの入門としてはいい課題だと思います。

**Comment by RyoheiGoto** [comment]
ありがとうございます!
逆ポーランド記法について調べて挑戦してみます

**Comment by ChisatoKasebayashi** [comment]
@DaikiMaekawa 前川先輩お久しぶりです!コメントありがとうございます。一年生への助言本当に助かります:sweat_drops:
逆ポーランド記法まだ少し調べただけなのですが面白そうです！！私も参加します、
来週に制御のテストがあるため早い完成は厳しそうですが:sweat:
先輩がお手隙のようでしたらまたコメントください

**Comment by DaikiMaekawa** [comment]
わかりました。 また時間があるときにコメントします。
