### ISSUE TITLE
任意の点でボールの色ヒストグラムを取得できるプログラムを作る

### ISSUE THREAD

**Issue by yotaseki** [ChisatoKasebayashi/Dorayaki#7]
### 目的
- 検出されない転がってるボールの色ヒストグラムを取ること
### 手順
- [x] 画像を表示する
- [x] YUVで表現 ,階調に注意する
- [x] クリックした点の座標を取得する
- [x] 検出範囲の円の半径の決定
- [x] 検出範囲の円を可視化する
- [x] ImageProcessing::getColorHistgramを転用
- [x] ヒストグラムをファイル出力する
- [x] しっかり睡眠をとる

**Comment by yotaseki** [comment]
![image00011-](https://cloud.githubusercontent.com/assets/7345154/8005189/0c64adb4-0bc2-11e5-9363-b4e5e3c58a59.png)

検出できなかったボールのサンプルです

**Comment by ChisatoKasebayashi** [comment]
画像表示はクリアね、src/for_1426/ImageProxessing/otamesi_hist.cppです

**Comment by ChisatoKasebayashi** [comment]
座標の取得もクリア、右クリックと左クリック両方使えます

**Comment by yotaseki** [comment]
これで残すはnormalizedHistgram[]をファイル出力する関数を追加することのみとなりました
それが終われば結果の確認・プログラムの改良を進めていきましょう

**Comment by ChisatoKasebayashi** [comment]
histogram_log.txtとして結果を出力しています
結果が気になるから普通にファイル出力のコード追加しただけだけど、これからの改良はなんかもっと汎用性の高い？便利な？関数にしたいなと思ってます。

**Comment by yotaseki** [comment]
いいね！:100: 
とりあえずこれで基本的な機能は完成しましたね
closeしましょう

**Comment by ChisatoKasebayashi** [comment]
まだ、しっかり睡眠をとる、が完了していません
